### ISSUE TITLE
Set up DNS for `geodetic-proposals.isotc211.org` to point to `isogr/registry-proposals` GitHub Pages

### ISSUE THREAD

**Issue by ribose-jeffreylau** [isogr/registry-proposals#1]

**Comment by kwkwan** [comment]
Closed as completed

**Comment by ribose-jeffreylau** [comment]
Thanks @kwkwan !  I think there's a regression in configuration, can you please check?

**Comment by kwkwan** [comment]
The Settings of the Pages shows "DNS check successful" and Enorce HTTPS is checked.

<img width="1254" alt="Screenshot 2024-10-08 at 8 26 07 AM" src="https://github.com/user-attachments/assets/80c39297-484c-44c3-b0cd-bc109acf68d5">

The CNAME of the record also shows:
```
geodetic-proposals.isotc211.org. 5 IN	CNAME	registry-proposals.github.io.
```

When I access the page, it shows

<img width="1254" alt="Screenshot 2024-10-08 at 8 25 29 AM" src="https://github.com/user-attachments/assets/08045f2b-e0a1-463b-aef1-a8c409f14fa7">

Is it correct?

**Comment by ribose-jeffreylau** [comment]
@kwkwan Thanks.  Not sure why on my end, it is still resolving to AWS:

```console
$ dig a registry-proposals.isotc211.org

; <<>> DiG 9.10.6 <<>> a registry-proposals.isotc211.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 23546
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;registry-proposals.isotc211.org. IN    A

;; AUTHORITY SECTION:
isotc211.org.           843     IN      SOA     ns-1418.awsdns-49.org. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400

;; Query time: 61 msec
;; SERVER: 192.168.10.1#53(192.168.10.1)
;; WHEN: Wed Oct 09 15:05:38 HKT 2024
;; MSG SIZE  rcvd: 142
```

**Comment by ribose-jeffreylau** [comment]
@kwkwan Thanks!  I think I made a mistake...  Closing as complete.
